version: 2.1

jobs:
  shared-config-job:
    docker:
      - image: cimg/node:17.9.1
    steps:
      - checkout
      - run:
          name: cat README
          command: cat README.md


workflows:
  shared-config-repo:
    jobs:
      - shared-config-job
