version: 2.1

# parameters:
#   workflow-filter-based-only-on-parameters:
#     type: boolean
#     default: false
#   enum-parameter:
#     type: enum
#     values: ["one", "two", "three"]
#     default: "two"
#   string-parameter:
#     type: string
#     default: "this-is-a-string"

parameters:
  image-tag:
    type: string
    default: "current"
  and-another:
    type: enum
    default: "env-c"
    enum: ["env-a", "env-b", "env-c", "env-d"]
    
jobs:
  shared-config-job:
    docker:
      - image: cimg/node:17.9.1
    steps:
      - checkout
      - run:
          name: cat README
          command: cat README.md


workflows:
  shared-config-repo:
    jobs:
      - shared-config-job
