version: 2.1

jobs:
  NEW-config-repo:
    docker:
      - image: cimg/node:17.9.1
    steps:
      - checkout
      - run:
          name: print-readme-of-checkout-repo
          command: cat README.md
      - run:
          name: config-repo
          command: echo "This config is defined in NEW-config-repo"


workflows:
  NEW-config-repo:
    jobs:
      - shared-config-job
